name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12" 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Added plotly to fix the import error
        pip install reflex pymongo python-dotenv bcrypt pylint plotly 

    - name: Lint with Pylint
      run: |
        # Disabling Reflex & PyMongo framework false-positives
        pylint farm/farm/ --errors-only --disable=E1120,E1121,E1101,E1136,E1135,E1130

    - name: Check for Broad Exceptions
      run: |
        # Enforces SRS Rule 5.4.5: Prohibits bare 'except:' clauses 
        grep -r "except:" farm/farm/ && exit 1 || exit 0